services:
  - type: web
    name: agromart
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn agric_website.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: store_db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: agric-website.onrender.com,localhost

databases:
  - name: store_db
    region: oregon
    plan: free